spring.application.name=carly

# Configuration Database Locale (Mode Fichier)
spring.datasource.url=jdbc:h2:file:./data/autoecole;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

spring.web.cors.allowed-origins=http://localhost:3000
